name: sequence_qc
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - pysam=0.15.4
  - pybedtools=0.8.1
  - pyfaidx=0.5.8
  - pytest=5.4.2
  - click=7.1.2
  - pysamstats=1.1.2
  - pandas=1.0.3
#  - matplotlib==3.3.0
  - plotly==4.9.0
  - scipy==1.6.2
